// ============================================================================
// File generated by AI - DO NOT EDIT DIRECTLY
// Edit Legal Project Facts Data (legal-project-facts.data.ts) instead and regenerate.
// Exception: Explicitly mark fields as TO_BE_RESEARCHED to guide the AI (micromanagement).
//
// This file acts as intermediate persistence and traceability layer between
// the legal project facts (legal/legal-project-facts.data.ts) and the final legal HTML documents.
//
// Legal Project Conclusions Data is automatically derived from the Legal Project Facts Data by giving them to an AI which does all the legal and internet research.
// This data is necessary to fill all legal documents.
// All values here are based on public information, legal research, and provider documentation,
// in conjunction with the Legal Project Facts Data.
// ============================================================================

import {
  DEFINED_BY_PARENT,
  DEFINED_PER_CHILD,
  LegalProjectConclusions,
  TO_BE_RESEARCHED,
} from './legal-project-conclusions.type';

// TODO legal: retention rates of all kinds of data must be documented somehow. which granularity makes sense?
// TODO legal: technically necessary vs. non-essential must be documented somehow. where and which granularity makes sense?
// TODO legal: unsure how to model/handel tracking before consent true/false. figure it out and implement.

export const legalProjectConclusionsData: LegalProjectConclusions = {
  project: {
    // reasons: [legalProjectFactsData.project.description]
    websiteType: 'informational',
  },

  // reasons: [legalProjectFactsData.operator]
  operator: {},

  // reasons: [legalProjectFactsData.audience]
  audience: {},

  userRelatedFeatures: {
    // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactEmail]
    publicContactEmail: {
      activityType: 'contact_requests',
      purpose: 'communication',
      dataCategories: ['contact_data', 'communication_data'],
    },

    // reasons: [legalProjectFactsData.userRelatedFeatures.publicContactPhone]
    publicContactPhone: {
      activityType: 'telephony',
      purpose: 'telephony',
      dataCategories: ['contact_data'],
    },

    // reasons: [legalProjectFactsData.userRelatedFeatures.contactForm]
    contactForm: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.otherForms]
    otherForms: [],

    // reasons: [legalProjectFactsData.userRelatedFeatures.userAccounts]
    userAccounts: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.newsletter]
    newsletter: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.uploads]
    uploads: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.payments]
    payments: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.booking]
    booking: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.liveChat]
    liveChat: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.communityFeatures]
    communityFeatures: null,

    // reasons: [legalProjectFactsData.userRelatedFeatures.contractsConcludedOnWebsite]
    contractsConcludedOnWebsite: null,
  },

  customImplementations: {
    // reasons: [legalProjectFactsData.customImplementations.serverLogs]
    serverLogs: null,
  },

  thirdParties: {
    github: {
      // reasons: [
      //   "GitHub General Privacy Statement (address): https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
      // ]
      officialCompanyName: 'GitHub, Inc.',
      // reasons: [
      //   "GitHub General Privacy Statement (address): https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
      // ]
      officialCompanyAddress:
        'GitHub, Inc. 88 Colin P. Kelly Jr. St., San Francisco, CA 94107, United States',

      legallyRelevantUrls: {
        // reasons: [
        //   "GitHub General Privacy Statement: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
        // ]
        'Privacy Policy':
          'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement',
        // reasons: [
        //   "GitHub Pages privacy: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
        // ]
        'GitHub Pages - Data Collection':
          'https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection',
        // reasons: [
        //   "GitHub Customer Terms (DPA availability): https://docs.github.com/en/site-policy/github-terms/github-customer-terms-of-service",
        // ]
        'Customer Terms':
          'https://docs.github.com/en/site-policy/github-terms/github-customer-terms-of-service',
      },

      subServicesOrFeatures: {
        githubPages: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages,
          //   "GitHub Pages logs IP addresses for security: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
          //   "GitHub international transfers (SCC + DPF): https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
          // ]
          recipientType: 'independent_controller',

          // reasons: [
          //   "GitHub international transfers section indicates processing incl. US: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
          // ]
          dataRecipientCountry: 'USA',

          // reasons: [
          //   "GitHub relies on SCC and states DPF compliance: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement",
          // ]
          transferSafeguard: ['DPF', 'SCC'],

          // reasons: [
          //   "GitHub Customer Terms: GitHub Data Protection Agreement applies to certain products/plans; GitHub.com free services are typically controller context: https://docs.github.com/en/site-policy/github-terms/github-customer-terms-of-service",
          // ]
          hasDpa: false,

          // reasons: [
          //   "Legitimate interest base commonly applied for basic website delivery/security logging (GDPR Art. 6(1)(f)); GitHub Pages notes security logging: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
          // ]
          legalBases: ['article_6_1_f'],

          // reasons: [legalProjectFactsData.thirdParties.github.subServicesOrFeatures.githubPages]
          activityType: [
            'hosting_and_infrastructure',
            'website_delivery_and_security',
          ],

          // reasons: [
          //   "GitHub Pages data collection for security: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
          // ]
          purposes: ['hosting', 'website_delivery', 'security'],

          // reasons: [
          //   "GitHub Pages logs IP addresses: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
          // ]
          personalDataCategories: [
            'online_identifier_data',
            'device_technical_data',
            'usage_behavior_data',
          ],

          // reasons: [
          //   "GitHub Pages logs IP addresses (server logs): https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection",
          // ]
          dataProcessing: {
            requestAndSecurityLogs: {
              name: 'request and security logs',
              technicallyNecessary: true,
              retention: TO_BE_RESEARCHED,
              serverLogs: true,
              cookies: [],
              localStorage: [],
              sessionStorage: [],
              indexedDb: [],
              serviceWorkerStorage: [],
              otherStorage: [],
            },
          },
        },
      },
    },

    cloudflare: {
      // reasons: [
      //   "Cloudflare GDPR Trust Hub: https://www.cloudflare.com/trust-hub/gdpr/",
      // ]
      officialCompanyName: 'Cloudflare, Inc.',
      // reasons: [
      //   "Cloudflare policies/contact: https://www.cloudflare.com/terms/",
      // ]
      officialCompanyAddress: '101 Townsend St, San Francisco, CA 94107, USA',

      legallyRelevantUrls: {
        // reasons: ["Cloudflare Privacy Policy: https://www.cloudflare.com/privacypolicy/"]
        'Privacy Policy': 'https://www.cloudflare.com/privacypolicy/',
        // reasons: ["Cloudflare Terms: https://www.cloudflare.com/terms/"]
        'Terms of Service': 'https://www.cloudflare.com/terms/',
        // reasons: [
        //   "Cloudflare GDPR Trust Hub (SCC + DPF, processing locations): https://www.cloudflare.com/trust-hub/gdpr/",
        // ]
        'GDPR / Trust Hub': 'https://www.cloudflare.com/trust-hub/gdpr/',
        // reasons: [
        //   "Cloudflare DPA (referenced from Trust Hub): https://www.cloudflare.com/trust-hub/gdpr/",
        // ]
        DPA: 'https://www.cloudflare.com/cloudflare-customer-dpa/',
        // reasons: [
        //   "Cloudflare Web Analytics: https://www.cloudflare.com/web-analytics/",
        // ]
        'Web Analytics': 'https://www.cloudflare.com/web-analytics/',
      },

      subServicesOrFeatures: {
        cloudflare: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare,
          //   "Cloudflare processes metadata in US and Europe; relies on SCC/DPF: https://www.cloudflare.com/trust-hub/gdpr/",
          // ]
          recipientType: DEFINED_PER_CHILD,

          // reasons: [
          //   "Cloudflare processes metadata in US and Europe: https://www.cloudflare.com/trust-hub/gdpr/",
          // ]
          dataRecipientCountry: 'USA (processing in U.S. and Europe)',

          // reasons: [
          //   "Cloudflare SCC + DPF: https://www.cloudflare.com/trust-hub/gdpr/",
          // ]
          transferSafeguard: ['DPF', 'SCC'],

          // reasons: [
          //   "Cloudflare provides standard customer DPA (processor context): https://www.cloudflare.com/cloudflare-customer-dpa/",
          // ]
          hasDpa: true,

          // reasons: [legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare]
          legalBases: DEFINED_PER_CHILD,

          // reasons: [legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare]
          activityType: DEFINED_PER_CHILD,

          // reasons: [legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare]
          purposes: DEFINED_PER_CHILD,

          // reasons: [legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare]
          personalDataCategories: DEFINED_PER_CHILD,

          // reasons: [legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare]
          dataProcessing: DEFINED_PER_CHILD,

          subServicesOrFeatures: {
            proxiedDns: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.proxiedDns,
              //   "Cloudflare processes network metadata (IP) on behalf of customers: https://www.cloudflare.com/trust-hub/gdpr/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: [
                'dns_and_network_routing',
                'website_delivery_and_security',
              ],
              purposes: ['network_routing', 'security'],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
              ],
              dataProcessing: {
                dnsRequestProcessing: {
                  name: 'DNS request processing',
                  technicallyNecessary: true,
                  retention: TO_BE_RESEARCHED,
                  serverLogs: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            dnsAnalytics: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.dnsAnalytics,
              //   "Cloudflare maintains and processes log metadata for limited time: https://www.cloudflare.com/trust-hub/gdpr/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: ['dns_and_network_routing', 'analytics'],
              purposes: ['analytics', 'security'],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
                'usage_behavior_data',
              ],
              dataProcessing: {
                dnsAnalytics: {
                  name: 'DNS analytics dashboards',
                  technicallyNecessary: true,
                  retention:
                    'Aggregate and log-based DNS analytics for operational visibility and security; underlying log metadata is processed for a limited period depending on Cloudflare settings.',
                  serverLogs: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            cdn: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.cdn,
              //   "Cloudflare processes request metadata incl. IP; content largely stays at edge; metadata in US/EU: https://www.cloudflare.com/trust-hub/gdpr/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: [
                'content_delivery',
                'website_delivery_and_security',
              ],
              purposes: [
                'content_delivery',
                'website_delivery',
                'security',
                'performance_optimization',
              ],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
                'usage_behavior_data',
                'location_data',
              ],
              dataProcessing: {
                cdnCachingAndDelivery: {
                  name: 'CDN caching and delivery',
                  technicallyNecessary: true,
                  retention: TO_BE_RESEARCHED,
                  serverLogs: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            httpTraffic: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.httpTraffic,
              //   "Cloudflare maintains log data incl. limited personal data (often IP): https://www.cloudflare.com/trust-hub/gdpr/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: ['website_delivery_and_security', 'analytics'],
              purposes: ['security', 'analytics', 'performance_optimization'],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
                'usage_behavior_data',
              ],
              dataProcessing: {
                httpTrafficAnalytics: {
                  name: 'HTTP traffic analytics/log insights',
                  technicallyNecessary: true,
                  retention: TO_BE_RESEARCHED,
                  serverLogs: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            performance: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.performance,
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: ['website_delivery_and_security', 'analytics'],
              purposes: ['performance_optimization', 'analytics'],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
                'usage_behavior_data',
              ],
              dataProcessing: {
                performanceDashboards: {
                  name: 'performance analytics dashboards',
                  technicallyNecessary: true,
                  retention:
                    'Performance metrics derived from request/usage metadata; retained according to Cloudflare analytics/log configuration.',
                  serverLogs: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            webAnalytics: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.webAnalytics,
              //   "Cloudflare Web Analytics is designed to be cookie-free: https://www.cloudflare.com/web-analytics/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: ['analytics'],
              purposes: ['analytics', 'performance_optimization'],
              personalDataCategories: [
                'usage_behavior_data',
                'device_technical_data',
                'online_identifier_data',
              ],
              dataProcessing: {
                webAnalytics: {
                  name: 'Cloudflare Web Analytics (JS)',
                  technicallyNecessary: false,
                  retention: TO_BE_RESEARCHED,
                  thirdPartyScripts: [
                    'Cloudflare Web Analytics JS snippet (auto-injected for non-EU visitors; not injected for EU visitors)',
                  ],
                  trackingBeforeConsent: true,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
              subServicesOrFeatures: {
                realUserMeasurements: {
                  // reasons: [
                  //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.webAnalytics.subServicesOrFeatures.realUserMeasurements,
                  // ]
                  recipientType: 'processor',
                  dataRecipientCountry: DEFINED_BY_PARENT,
                  transferSafeguard: DEFINED_BY_PARENT,
                  hasDpa: DEFINED_BY_PARENT,
                  legalBases: ['article_6_1_f'],
                  activityType: ['analytics'],
                  purposes: ['analytics', 'performance_optimization'],
                  personalDataCategories: [
                    'usage_behavior_data',
                    'device_technical_data',
                    'online_identifier_data',
                  ],
                  dataProcessing: {
                    rum: {
                      name: 'Real User Measurements (RUM)',
                      technicallyNecessary: false,
                      retention: TO_BE_RESEARCHED,
                      thirdPartyScripts: [
                        'Cloudflare RUM / Web Analytics JS (auto-injected for non-EU visitors; not injected for EU visitors)',
                      ],
                      trackingBeforeConsent: true,
                      cookies: [],
                      localStorage: [],
                      sessionStorage: [],
                      indexedDb: [],
                      serviceWorkerStorage: [],
                      otherStorage: [],
                    },
                  },
                },
              },
            },

            emailRouting: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.emailRouting,
              //   "Cloudflare Email Routing feature docs: https://developers.cloudflare.com/email-routing/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_b'],
              activityType: ['customer_communication'],
              purposes: ['communication', 'spam_prevention', 'security'],
              personalDataCategories: ['contact_data', 'communication_data'],
              dataProcessing: {
                emailForwarding: {
                  name: 'email forwarding/routing',
                  technicallyNecessary: true,
                  retention: TO_BE_RESEARCHED,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            dmarcManagement: {
              // reasons: [
              //   legalProjectFactsData.thirdParties.cloudflare.subServicesOrFeatures.cloudflare.subServicesOrFeatures.dmarcManagement,
              //   "Cloudflare DMARC Management processes DMARC reports on customer behalf: https://developers.cloudflare.com/dmarc-management/enable/",
              // ]
              recipientType: 'processor',
              dataRecipientCountry: DEFINED_BY_PARENT,
              transferSafeguard: DEFINED_BY_PARENT,
              hasDpa: DEFINED_BY_PARENT,
              legalBases: ['article_6_1_f'],
              activityType: ['website_delivery_and_security'],
              purposes: ['security', 'fraud_prevention'],
              personalDataCategories: [
                'online_identifier_data',
                'device_technical_data',
              ],
              dataProcessing: {
                dmarcReports: {
                  name: 'DMARC report processing',
                  technicallyNecessary: true,
                  retention: TO_BE_RESEARCHED,
                  cookies: [],
                  localStorage: [],
                  sessionStorage: [],
                  indexedDb: [],
                  serviceWorkerStorage: [],
                  otherStorage: [],
                },
              },
            },

            waf: null,
            botFightMode: null,
            superBotFightMode: null,
            rateLimiting: null,
            turnstile: null,
            zaraz: null,
            waitingRoom: null,
            loadBalancer: null,
          },
        },
      },
    },

    smtp2go: {
      // reasons: [
      //   "SMTP2GO Privacy Policy (company details): https://www.smtp2go.com/privacy-policy",
      // ]
      officialCompanyName: 'Sand Dune Mail Ltd.',
      // reasons: [
      //   "SMTP2GO Privacy Policy (company details): https://www.smtp2go.com/privacy-policy",
      // ]
      officialCompanyAddress:
        'Sand Dune Mail Ltd., 96-106 Manchester Street, Christchurch 8011, New Zealand',

      legallyRelevantUrls: {
        // reasons: ["SMTP2GO Privacy Policy: https://www.smtp2go.com/privacy-policy"]
        'Privacy Policy': 'https://www.smtp2go.com/privacy-policy',
        // reasons: ["SMTP2GO Terms: https://www.smtp2go.com/terms/"]
        Terms: 'https://www.smtp2go.com/terms/',
        // reasons: [
        //   "SMTP2GO Vendor Info (DPA + retention): https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information",
        // ]
        'Vendor Information (DPA/Retention)':
          'https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information',
        // reasons: [
        //   "SMTP2GO EU Data Center: https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
        // ]
        'EU Data Center':
          'https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center',
      },

      subServicesOrFeatures: {
        smtp2go: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go,
          //   "SMTP2GO provides DPA in dashboard: https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information",
          //   "EU data center + deletion after 35 days default: https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
          // ]
          recipientType: 'processor',

          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go.notes,
          //   "SMTP2GO EU data center in Amsterdam for EU/UK customers: https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
          // ]
          dataRecipientCountry: 'EU (Amsterdam)',

          // reasons: [
          //   "EU processing stated for EU/UK SMTP services: https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
          // ]
          transferSafeguard: ['none'],

          // reasons: [
          //   legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go.notes,
          //   "SMTP2GO provides DPA in dashboard: https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information",
          // ]
          hasDpa: true,

          // reasons: [legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go]
          legalBases: ['article_6_1_b'],

          // reasons: [legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go]
          activityType: ['customer_communication'],

          // reasons: [legalProjectFactsData.thirdParties.smtp2go.subServicesOrFeatures.smtp2go]
          purposes: ['communication', 'support'],

          // reasons: [
          //   "SMTP2GO processes email activity/log data and (optionally) content when enabled; default is activity-level storage: https://support.smtp2go.com/hc/en-gb/articles/14855846048665-Vendor-Information",
          // ]
          personalDataCategories: [
            'contact_data',
            'communication_data',
            'online_identifier_data',
          ],

          // reasons: [
          //   "Default deletion after 35 days; visibility differs by plan: https://support.smtp2go.com/hc/en-gb/articles/12974008254873-EU-Data-Center",
          // ]
          dataProcessing: {
            outboundEmailDelivery: {
              name: 'email sending / delivery logs',
              technicallyNecessary: true,
              retention:
                'SMTP2GO states activity data is deleted after 35 days by default; paid plans can extend retention; optional email archiving is a separate paid feature.',
              cookies: [],
              localStorage: [],
              sessionStorage: [],
              indexedDb: [],
              serviceWorkerStorage: [],
              otherStorage: [],
            },
          },
        },
      },
    },

    google: {
      // reasons: [
      //   "Google Germany legal notice (Diensteanbieterin): https://www.google.de/contact/impressum.html",
      // ]
      officialCompanyName: 'Google Ireland Limited',
      // reasons: [
      //   "Google Germany legal notice: https://www.google.de/contact/impressum.html",
      // ]
      officialCompanyAddress: 'Gordon House, Barrow Street, Dublin 4, Ireland',

      legallyRelevantUrls: {
        // reasons: ["Google Privacy Policy: https://policies.google.com/privacy"]
        'Privacy Policy': 'https://policies.google.com/privacy',
        // reasons: ["Google Terms: https://policies.google.com/terms"]
        'Terms of Service': 'https://policies.google.com/terms',
        // reasons: [
        //   "Google data transfer frameworks (DPF + SCC): https://policies.google.com/privacy/frameworks?hl=en-US",
        // ]
        'Data transfer frameworks':
          'https://policies.google.com/privacy/frameworks?hl=en-US',
        // reasons: [
        //   "Google Germany legal notice: https://www.google.de/contact/impressum.html",
        // ]
        'Legal notice (DE)': 'https://www.google.de/contact/impressum.html',
      },

      subServicesOrFeatures: {
        gmail: {
          // reasons: [
          //   legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail,
          //   "Google consumer services EU controller is Google Ireland Limited: https://policies.google.com/faq?hl=en",
          // ]
          recipientType: 'independent_controller',

          // reasons: [
          //   "Google maintains servers around the world; processing may occur outside country: https://policies.google.com/privacy/frameworks?hl=en-US",
          // ]
          dataRecipientCountry: 'Ireland / USA (global processing)',

          // reasons: [
          //   "Google DPF certification + SCCs described: https://policies.google.com/privacy/frameworks?hl=en-US",
          // ]
          transferSafeguard: ['DPF', 'SCC'],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail.notes]
          hasDpa: false,

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          legalBases: ['article_6_1_b'],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          activityType: ['customer_communication', 'contact_requests'],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          purposes: ['communication', 'support', 'storage'],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          personalDataCategories: ['contact_data', 'communication_data'],

          // reasons: [legalProjectFactsData.thirdParties.google.subServicesOrFeatures.gmail]
          dataProcessing: {
            mailboxStorage: {
              name: 'email mailbox storage and processing',
              technicallyNecessary: true,
              retention:
                'Emails and related communication content are stored in the mailbox until deleted in the course of handling the request and according to internal retention practices.',
              cookies: [],
              localStorage: [],
              sessionStorage: [],
              indexedDb: [],
              serviceWorkerStorage: [],
              otherStorage: [],
            },
          },
        },
      },
    },

    blau: {
      // reasons: ["Blau privacy: https://www.blau.de/datenschutz"]
      officialCompanyName: 'Telefónica Germany GmbH & Co. OHG',
      // reasons: ["Telefónica Germany corporate address is commonly published; Blau privacy page as baseline: https://www.blau.de/datenschutz"]
      officialCompanyAddress: 'Georg-Brauchle-Ring 50, 80992 München, Germany',

      legallyRelevantUrls: {
        // reasons: ["Blau privacy: https://www.blau.de/datenschutz"]
        'Privacy Policy': 'https://www.blau.de/datenschutz',
      },

      subServicesOrFeatures: {
        simCardAndMobilePhoneNumber: {
          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          recipientType: 'independent_controller',

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          dataRecipientCountry: 'Germany / EU',

          // reasons: ["Within EU/EEA: no third-country safeguard required."]
          transferSafeguard: ['none'],

          // reasons: ["Telecom provider is its own controller; no DPA."]
          hasDpa: false,

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          legalBases: ['article_6_1_b', 'article_6_1_f'],

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          activityType: ['telephony'],

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          purposes: ['telephony', 'communication'],

          // reasons: [legalProjectFactsData.thirdParties.blau.subServicesOrFeatures.simCardAndMobilePhoneNumber]
          personalDataCategories: ['contact_data'],

          // reasons: ["Telephony provider processes connection/traffic data per telecom contract; retention per provider policies."]
          dataProcessing: {
            callHandling: {
              name: 'telephony connection handling',
              technicallyNecessary: true,
              retention:
                'Connection/traffic data is processed by the telecommunications provider in accordance with provider policies and applicable telecom regulations; we do not store call recordings.',
              cookies: [],
              localStorage: [],
              sessionStorage: [],
              indexedDb: [],
              serviceWorkerStorage: [],
              otherStorage: [],
            },
          },
        },
      },
    },
  },

  requiredDocuments: {
    // reasons: ["DDG § 5 (provider identification): https://www.gesetze-im-internet.de/ddg/__5.html"]
    imprint: true,

    // reasons: ["GDPR Art. 13 information duties: https://eur-lex.europa.eu/eli/reg/2016/679/oj"]
    privacyPolicy: true,

    // reasons: [legalProjectFactsData.userRelatedFeatures.contractsConcludedOnWebsite]
    termsAndConditions: false,

    // reasons: ["DPAs are internal contracts, not user-facing documents in this setup."]
    dataProcessingAgreement: false,

    // reasons: [
    //   "No marketing/analytics cookies identified (Cloudflare Web Analytics is cookie-free per provider marketing); cookie details can be handled within privacy policy.",
    // ]
    cookiePolicy: false,

    // reasons: [legalProjectFactsData.project.description, "BFSG applies to specific covered services/products; informational portfolio typically not in scope."]
    accessibilityStatement: false,
  },
};
