import { Project } from './project';

export const ALL_PROJECTS: Project[] = [
  {
    id: 'language-learning-app',
    title: 'AI-Powered Language Learning App',
    projectType: 'Mobile & Web Application',
    compactDescription:
      'Revolutionary language learning app that generates picture-based stories using AI, automatically adapting to user learning levels.',
    keyAchievements:
      'Full-stack ownership • AI story generation • Multi-platform deployment • Adaptive learning algorithm',
    fullDescription:
      "Development of a comprehensive language learning application for all languages that generates picture-based stories using AI. The app automatically adapts to the user's learning level and offers extensive customization options. Focus on reading comprehension and listening comprehension with autonomous development responsibility covering planning, development, testing, maintenance, and legal aspects.",
    features: [
      'AI-Generated Picture Stories',
      'Adaptive Learning Algorithm',
      'Multi-language Support',
      'Reading Comprehension Focus',
      'Listening Comprehension Training',
      'User Progress Tracking',
      'Customizable Learning Paths',
      'Cross-platform Compatibility',
    ],
    highlights: [
      'Solely responsible for entire application lifecycle',
      'Implemented AI-powered content generation using OpenAI',
      'Built scalable cloud infrastructure on AWS',
      'Developed cross-platform mobile app with React Native',
    ],
    technologies: [
      'Java',
      'Spring Boot',
      'React Native',
      'AWS',
      'OpenAI',
      'Expo',
      'TypeScript',
      'Redux',
      'Sentry',
      'GitHub',
      'npm',
      'Maven',
      'Mono Repo',
      'DynamoDB',
      'S3',
      'CDK',
      'CloudFormation',
      'CloudWatch',
      'AppConfig',
      'Elastic Beanstalk',
      'API Gateway',
      'IAM',
      'IAM Identity Center',
      'AWS Organizations',
      'Polly',
    ],
    role: 'Project Manager & Full-Stack Developer',
    team: 'Solo development',
    fromTo: '08/2023 – Present',
    duration: '1 year 10 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Oliver Stadie IT GmbH',
    industry: 'Education Technology',
  },
  {
    id: 'lottery-websites',
    title: 'Enterprise Lottery Platform',
    projectType: 'Micro-Frontend Web Application',
    compactDescription:
      'Maintenance and improvement of complex lottery websites with custom frontend framework and Micro-Frontend architecture.',
    keyAchievements:
      'Custom CI/CD tool development • Web vitals optimization • Team consulting • Technical project management',
    fullDescription:
      'Maintained and improved existing lottery websites in a Scrum-like environment. Worked on the custom frontend framework of a complex Micro-Frontend architectured Online Shop for multiple lottery platforms. Provided consulting to team and served as Technical Project Manager while building a custom CI/CD tool to ensure optimal website performance through web vitals monitoring.',
    features: [
      'Micro-Frontend Architecture',
      'Custom Frontend Framework',
      'Multi-lottery Platform',
      'Performance Monitoring',
      'CI/CD Pipeline',
      'Web Vitals Optimization',
      'Complex Online Shop',
      'Scrum Workflow Integration',
    ],
    highlights: [
      'Built custom CI/CD tool for performance monitoring',
      'Optimized web vitals across multiple lottery platforms',
      'Provided technical consulting and project management',
      'Worked with complex Micro-Frontend architecture',
    ],
    technologies: [
      'Angular 13',
      'Node.js',
      'NestJS',
      'TypeScript',
      'RxJS',
      'nx',
      'SCSS',
      'HTML',
      'CSS',
      'Jest',
      'Cypress',
      'Sentry',
      'GitHub',
      'Jira',
      'Confluence',
      'npm',
      'yarn',
      'Docker',
      'Kubernetes',
      'Java',
      'Spring Boot',
      'Lighthouse',
      'Web Vitals',
      'Puppeteer',
      'Micro Frontends',
      'Microservices',
      'Jenkins',
      'Redash',
      'SQL',
      'DataDog',
      'Splunk',
      'GTM',
    ],
    role: 'Web Developer & Technical Project Manager',
    team: 'Large Scrum team',
    fromTo: '08/2021 – 06/2022',
    duration: '11 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Large Lottery Company',
    industry: 'eCommerce / Gaming',
  },
  {
    id: 'unicorn-ecommerce',
    title: 'Custom E-Commerce Framework Development',
    projectType: 'E-Commerce Web Application',
    compactDescription:
      "Building and maintaining online shops for 3rd party customers using a major e-commerce company's custom framework.",
    keyAchievements:
      'Multi-client platform development • Cross-team collaboration • Custom framework expertise • Designer integration',
    fullDescription:
      "Built and maintained online shops for various 3rd party customers using a major e-commerce company's proprietary framework. Collaborated closely with designers, customers, other technical teams, and suppliers to deliver customized shopping experiences. Focused on creating scalable and maintainable solutions within the existing framework ecosystem.",
    features: [
      'Custom E-Commerce Framework',
      'Multi-client Architecture',
      'Third-party Integrations',
      'Responsive Design',
      'Customer-specific Customizations',
      'Supplier Integration',
      'Performance Optimization',
      'Cross-platform Compatibility',
    ],
    highlights: [
      'Delivered multiple client projects within framework constraints',
      'Collaborated effectively with diverse stakeholder groups',
      'Maintained high code quality in complex framework environment',
      'Implemented customer-specific requirements efficiently',
    ],
    technologies: [
      'Angular',
      'Node.js',
      'Express',
      'TypeScript',
      'RxJS',
      'nx',
      'SCSS',
      'HTML',
      'CSS',
      'Jest',
      'Jasmine',
      'Cypress',
      'Karma',
      'AWS',
      'Sentry',
      'GitLab',
      'Jira',
      'Confluence',
      'npm',
    ],
    role: 'Web Developer',
    team: 'Cross-functional team',
    fromTo: '04/2020 – 05/2021',
    duration: '1 year 2 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Major E-Commerce Platform',
    industry: 'E-Commerce',
  },
  {
    id: 'insurance-calculator',
    title: 'Insurance Calculation & Contract Platform',
    projectType: 'Web Application',
    compactDescription:
      'Complex insurance calculation website with contract closing functionality and advanced form validation.',
    keyAchievements:
      'Complex form development • Insurance price calculation • Data verification • Custom component library usage',
    fullDescription:
      'Developed a comprehensive website for calculating insurance premiums and closing contracts digitally. Created complex forms to calculate insurance prices, verify input data, and guide users through the contract process. Utilized an existing custom web component library to maintain consistency and efficiency in development.',
    features: [
      'Insurance Price Calculator',
      'Contract Closing System',
      'Complex Form Validation',
      'Data Verification',
      'Custom Web Components',
      'User Guidance System',
      'Responsive Design',
      'Multi-step Workflows',
    ],
    highlights: [
      'Implemented sophisticated calculation algorithms',
      'Built complex multi-step form workflows',
      'Integrated with existing component library effectively',
      'Delivered accurate insurance pricing functionality',
    ],
    technologies: [
      'Angular',
      'TypeScript',
      'SASS',
      'HTML5',
      'CSS',
      'JavaScript',
      'Stencil',
      'Fractal',
      'Lodash',
      'Jasmine',
      'Karma',
      'Node.js',
      'Express',
      'GitHub',
      'Jira',
      'Confluence',
      'TFS',
      'npm',
    ],
    role: 'Web Developer',
    team: 'Development team',
    fromTo: '08/2019 – 11/2019',
    duration: '4 months',
    location: 'Berlin, Germany',
    workMode: 'On-site',
    company: 'edenspiekermann',
    industry: 'Insurance',
  },
  {
    id: 'fintech-portfolio-management',
    title: 'B2B Financial Portfolio Management Platform',
    projectType: 'B2B Web Application',
    compactDescription:
      'Backend development for banks and portfolio managers to manage financial products with REST APIs and microservices architecture.',
    keyAchievements:
      'Microservices architecture • REST API development • Message broker implementation • CI/CD setup',
    fullDescription:
      'Built and improved a comprehensive B2B platform enabling banks and portfolio managers to efficiently manage financial products. Provided REST endpoints and Message Broker integration for frontend and other microservices. Established initial architecture patterns and workflows including testing frameworks and CI/CD pipelines for scalable fintech operations.',
    features: [
      'Financial Product Management',
      'REST API Endpoints',
      'Message Broker Integration',
      'Microservices Architecture',
      'Bank Integration',
      'Portfolio Management Tools',
      'Automated Testing',
      'CI/CD Pipeline',
    ],
    highlights: [
      'Architected initial microservices infrastructure',
      'Implemented robust message broker communication',
      'Established comprehensive testing and deployment workflows',
      'Built scalable REST API architecture',
    ],
    technologies: [
      'Node.js',
      'Express',
      'GraphQL',
      'TypeScript',
      'Mocha',
      'Chai',
      'Jasmine',
      'Jest',
      'RabbitMQ',
      'MongoDB',
      'Docker',
      'Yarn',
      'JSON',
      'GitLab',
    ],
    role: 'B2B Back-End Web Developer',
    team: 'Backend development team',
    fromTo: '04/2018 – 12/2018',
    duration: '9 months',
    location: 'Multiple locations and remote',
    workMode: 'Hybrid',
    company: 'vestr',
    industry: 'FinTech',
  },
  {
    id: 'airberlin-booking-app',
    title: 'Flight Booking Application Frontend',
    projectType: 'Web Application',
    compactDescription:
      'Frontend maintenance and improvement of high-traffic flight booking application in Scrum environment.',
    keyAchievements:
      'High-traffic optimization • Multi-team coordination • Scrum implementation • Performance under pressure',
    fullDescription:
      'Maintained and improved the frontend of a new flight booking application in a high-traffic, high-turnover environment using Scrum methodology. Coordinated effectively with multiple teams including UI/UX, Backend, and Operations to ensure seamless user experience and system reliability during peak booking periods.',
    features: [
      'Flight Booking Interface',
      'High-traffic Optimization',
      'Real-time Availability',
      'Payment Integration',
      'Multi-team Coordination',
      'Performance Monitoring',
      'User Experience Focus',
      'Scrum Implementation',
    ],
    highlights: [
      'Maintained performance in high-traffic environment',
      'Coordinated effectively across multiple technical teams',
      'Delivered improvements under tight airline industry deadlines',
      'Implemented Scrum practices for rapid development cycles',
    ],
    technologies: [
      'AngularJS',
      'SASS',
      'HTML5',
      'CSS',
      'JavaScript',
      'jQuery',
      'Lodash',
      'npm',
      'Grunt',
      'Bower',
      'Jasmine',
      'Karma',
      'Zeplin',
      'JIRA',
      'Confluence',
      'BitBucket',
    ],
    role: 'Web Developer',
    team: 'Scrum team with multiple departments',
    fromTo: '05/2017 – 08/2017',
    duration: '4 months',
    location: 'Berlin, Germany',
    workMode: 'On-site',
    company: 'AirBerlin',
    industry: 'Airline / eCommerce',
  },
  {
    id: 'self-driving-car-demo',
    title: 'Self-Driving Car Control Demo App',
    projectType: 'Cross-Platform Mobile Application',
    compactDescription:
      'Demo application for controlling autonomous vehicle prototype with route programming and media control capabilities.',
    keyAchievements:
      'Autonomous vehicle integration • Cross-platform development • UI/UX collaboration • International teamwork',
    fullDescription:
      'Developed a demonstration application to control a visionary self-driving car prototype with cross-platform compatibility, especially for iOS. Provided functionality to program the route the car would drive autonomously and control various car media systems including lighting and music. Collaborated closely with multiple UI/UX designers and Chinese consultants in an international development environment.',
    features: [
      'Autonomous Route Programming',
      'Car Media Control',
      'Light System Control',
      'Music System Integration',
      'Cross-platform Compatibility',
      'iOS Optimization',
      'Real-time Car Communication',
      'Intuitive User Interface',
    ],
    highlights: [
      'Integrated with cutting-edge autonomous vehicle technology',
      'Delivered cross-platform mobile solution with iOS focus',
      'Collaborated in international, multicultural team environment',
      'Implemented innovative car control interfaces',
    ],
    technologies: [
      'Angular',
      'TypeScript',
      'HTML5',
      'CSS',
      'JavaScript',
      'Ionic',
      'Cordova',
      'GitLab',
      'npm',
      'Webpack',
      'iOS',
      'XCode',
      'Swiper',
    ],
    role: 'Mobile App Developer',
    team: 'International team with UI/UX designers',
    fromTo: '03/2017 – 04/2017',
    duration: '2 months',
    location: 'Potsdam, Germany',
    workMode: 'On-site',
    company: "World's Largest Car Maker",
    industry: 'Automotive',
  },
  {
    id: 'freelancing-it-professional',
    title: 'Freelancing IT Professional',
    projectType: 'Various Projects',
    compactDescription:
      'Long-term freelancing career delivering diverse IT solutions across multiple industries and technologies.',
    keyAchievements:
      '25+ years experience • Multi-industry expertise • Technology adaptation • Independent project delivery',
    fullDescription:
      'Extensive freelancing career spanning over two decades, delivering diverse IT solutions across multiple industries. Demonstrated ability to adapt to new technologies, work independently, manage client relationships, and deliver high-quality solutions across various project types and technological stacks.',
    features: [
      'Multi-industry Experience',
      'Technology Adaptation',
      'Independent Project Management',
      'Client Relationship Management',
      'Diverse Solution Delivery',
      'Continuous Learning',
      'Quality Assurance',
      'Flexible Engagement Models',
    ],
    highlights: [
      'Successfully delivered projects across 25+ years',
      'Adapted to evolving technology landscape',
      'Built strong client relationships and repeat business',
      'Maintained high quality standards across all engagements',
    ],
    technologies: [
      'Various Technologies',
      'Web Development',
      'Mobile Development',
      'Backend Systems',
      'Frontend Frameworks',
      'Database Systems',
      'Cloud Platforms',
      'DevOps Tools',
      'Project Management',
      'Quality Assurance',
    ],
    role: 'Freelancing IT Professional',
    team: 'Various team configurations',
    fromTo: 'Since 2000',
    duration: '25+ years',
    location: 'Various locations',
    workMode: 'Flexible',
    company: 'Independent / Various Clients',
    industry: 'Various Industries',
  },
];
