import { TagName } from '@portfolio/taxonomy';

export interface ProjectData {
  id: string;
  title: string;
  projectType: string;
  compactDescription: string;
  keyAchievements: string;
  fullDescription: string;
  features: string[];
  highlights: string[];
  technologies: TagName[];
  role: string;
  team: string;
  fromTo: string;
  duration: string;
  location: string;
  workMode: string;
  company: string;
  industry: string; // TODO taxonomy: consider adding industries to the taxonomy to match/highlight them
}

export const ALL_PROJECT_DATA: ProjectData[] = [
  {
    id: 'language-learning-app',
    title: 'AI-Powered Language Learning App',
    projectType: 'Mobile App',
    compactDescription:
      'Revolutionary language learning app that generates picture-based stories using AI, automatically adapting to user learning levels.',
    keyAchievements:
      'Full-stack ownership • AI story generation • Automatic internationalization • Adaptive learning algorithm',
    fullDescription:
      "Development of a comprehensive language learning application for all languages that generates picture-based stories using AI. The app automatically adapts to the user's learning level and offers extensive customization options. Focus on reading comprehension and listening comprehension with autonomous development responsibility covering planning, development, testing, maintenance, and legal aspects.",
    features: [
      'AI-generated stories with pictures and audio',
      'Adaptive learning algorithm',
      'Fully automatic multi-language support',
      'Reading comprehension focus',
      'Listening comprehension training',
      'User progress tracking',
    ],
    highlights: [
      'Solely responsible for entire application lifecycle',
      'Implemented AI-powered content generation using multiple AI providers',
      'Built scalable cloud infrastructure on AWS',
      'Developed cross-platform mobile app',
    ],
    technologies: [
      'Java',
      'Spring Boot',
      'React Native',
      'AWS',
      'OpenAI',
      'Expo',
      'TypeScript',
      'Redux',
      'Sentry',
      'GitHub',
      'npm',
      'Maven',
      'Mono Repo',
      'DynamoDB',
      'S3',
      'CDK',
      'CloudFormation',
      'CloudWatch',
      'AppConfig',
      'Elastic Beanstalk',
      'API Gateway',
      'IAM',
      'IAM Identity Center',
      'AWS Organizations',
      'Polly',
    ],
    role: 'Project Manager & Full-Stack Developer',
    team: 'Solo development',
    fromTo: '08/2024 – Present',
    duration: '1 year 11 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Oliver Stadie IT GmbH',
    industry: 'Education Technology',
  },
  {
    id: 'lottery-websites',
    title: 'Enterprise Lottery Platform',
    projectType: 'Web App',
    compactDescription:
      'Maintenance and improvement of complex lottery websites with custom frontend framework and micro-frontend architecture.',
    keyAchievements:
      'Custom CI/CD tool development • Web vitals performance optimization • Technical consulting',
    fullDescription:
      'Maintained and improved existing lottery websites in a Scrum-like environment. Worked on the custom frontend framework of a complex micro-frontend architectured online shop for multiple lottery platforms. Provided technical consulting to team and managers while building a custom CI/CD tool to ensure company-wide optimal website performance through web vitals monitoring.',
    features: [
      'Micro-frontend architecture',
      'Custom frontend framework',
      'Multi-lottery platform',
      'Performance monitoring',
      'CI/CD pipeline',
      'Web vitals optimization',
      'Complex online shop',
      'Scrum workflow integration',
    ],
    highlights: [
      'Built custom CI/CD tool for performance monitoring',
      'Optimized web vitals across multiple lottery platforms',
      'Provided technical consulting',
      'Worked with complex micro-frontend architecture',
    ],
    technologies: [
      'Angular',
      'Node.js',
      'NestJS',
      'TypeScript',
      'RxJS',
      'Nx',
      'SCSS',
      'HTML',
      'CSS',
      'Jest',
      'Cypress',
      'Sentry',
      'GitHub',
      'Jira',
      'Confluence',
      'npm',
      'yarn',
      'Docker',
      'Kubernetes',
      'Java',
      'Spring Boot',
      'Lighthouse',
      'Web Vitals',
      'Puppeteer',
      'Micro Frontends',
      'Microservices',
      'Jenkins',
      'Redash',
      'SQL',
      'DataDog',
      'Splunk',
      'GTM',
    ],
    role: 'Web Developer & Technical Consultant',
    team: 'Large Scrum Team',
    fromTo: '08/2021 – 06/2022',
    duration: '11 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Large Lottery Company',
    industry: 'eCommerce / Gaming',
  },
  {
    id: 'unicorn-ecommerce',
    title: 'Custom E-Commerce Framework Development',
    projectType: 'Web App',
    compactDescription:
      "Building and maintaining online shops for third-party customers using a major e-commerce company's custom framework.",
    keyAchievements:
      'Multi-client platform development • Cross-team collaboration • Custom CMS integration • Regular on-time delivery • Analytics • SEO',
    fullDescription:
      "Built and maintained online shops for various third-party customers using a major e-commerce company's proprietary framework. Collaborated closely with designers, customers, other technical teams, and suppliers to deliver customized shopping experiences. Focused on creating scalable and maintainable solutions within the existing framework ecosystem.",
    features: [
      'Custom e-commerce framework',
      'Custom CMS',
      'Multi-client architecture',
      'Third-party integrations',
      'Responsive design',
      'Customer-specific customizations',
      'Supplier integration',
      'Performance optimization',
      'Cross-platform compatibility',
    ],
    highlights: [
      'Delivered multiple client projects within framework constraints',
      'Collaborated effectively with diverse stakeholder groups',
      'Implemented customer-specific requirements efficiently',
    ],
    technologies: [
      'Angular',
      'Node.js',
      'Express',
      'TypeScript',
      'RxJS',
      'Nx',
      'SCSS',
      'HTML',
      'CSS',
      'Jest',
      'Jasmine',
      'Cypress',
      'Karma',
      'AWS',
      'Sentry',
      'GitLab',
      'Jira',
      'Confluence',
      'npm',
    ],
    role: 'Web Developer',
    team: 'Cross-functional Team',
    fromTo: '04/2020 – 05/2021',
    duration: '1 year 2 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Unicorn E-Commerce Startup',
    industry: 'E-Commerce',
  },
  {
    id: 'insurance-calculator',
    title: 'Insurance Calculation & Contract Platform',
    projectType: 'Web App',
    compactDescription:
      'Complex insurance calculation website with contract closing functionality and advanced form validation.',
    keyAchievements:
      'Complex form development • Insurance price calculation • Data verification • Custom component library usage',
    fullDescription:
      'Developed a comprehensive website for calculating insurance premiums and closing contracts digitally. Created complex forms to calculate insurance prices, verify input data, and guide users through the contract process. Utilized an existing custom web component library to maintain consistency and efficiency in development.',
    features: [
      'Insurance price calculator',
      'Contract closing system',
      'Complex form validation',
      'Data verification',
      'Custom web components',
      'User guidance system',
      'Responsive design',
      'Multi-step workflows',
    ],
    highlights: [
      'Implemented sophisticated calculation algorithms',
      'Built complex multi-step form workflows',
      'Integrated with existing component library effectively',
      'Delivered accurate insurance pricing functionality',
    ],
    technologies: [
      'Angular',
      'TypeScript',
      'SASS',
      'HTML5',
      'CSS',
      'JavaScript',
      'Stencil',
      'Fractal',
      'Lodash',
      'Jasmine',
      'Karma',
      'Node.js',
      'Express',
      'GitHub',
      'Jira',
      'Confluence',
      'TFS',
      'npm',
    ],
    role: 'Web Developer',
    team: 'Development Team',
    fromTo: '08/2019 – 11/2019',
    duration: '4 months',
    location: 'Berlin, Germany',
    workMode: 'On-site',
    company: 'edenspiekermann',
    industry: 'Insurance',
  },
  {
    id: 'fintech-portfolio-management',
    title: 'B2B Financial Portfolio Management Platform',
    projectType: 'Web App Backend',
    compactDescription:
      'Backend development for banks and portfolio managers to manage financial products with REST APIs and microservices architecture.',
    keyAchievements:
      'Microservices architecture • REST API development • Message broker implementation • CI/CD setup',
    fullDescription:
      'Built and improved a comprehensive B2B platform enabling banks and portfolio managers to efficiently manage financial products. Provided REST endpoints and message broker integration for frontend and other microservices. Established initial architecture patterns and workflows including testing frameworks and CI/CD pipelines for scalable fintech operations.',
    features: [
      'Financial product management',
      'REST API endpoints',
      'Message broker integration',
      'Microservices architecture',
      'Bank integration',
      'Portfolio management tools',
      'Automated testing',
      'CI/CD pipeline',
    ],
    highlights: [
      'Architected initial microservices infrastructure',
      'Implemented robust message broker communication',
      'Established comprehensive testing and deployment workflows',
      'Built scalable REST API architecture',
    ],
    technologies: [
      'Node.js',
      'Express',
      'GraphQL',
      'TypeScript',
      'mocha',
      'chai',
      'Jasmine',
      'Jest',
      'RabbitMQ',
      'MongoDB',
      'Docker',
      'yarn',
      'JSON',
      'GitLab',
    ],
    role: 'Backend Developer',
    team: 'Backend Development Team',
    fromTo: '04/2018 – 12/2018',
    duration: '9 months',
    location: 'Multiple locations and remote',
    workMode: 'Hybrid',
    company: 'vestr',
    industry: 'FinTech Startup',
  },
  {
    id: 'airberlin-booking-app',
    title: 'Flight Booking Application Frontend',
    projectType: 'Web App',
    compactDescription:
      'Frontend maintenance and improvement of high-traffic flight booking application in Scrum environment.',
    keyAchievements:
      'High-traffic, high-revenue environment • Multi-team coordination • Scrum implementation',
    fullDescription:
      'Maintained and improved the frontend of a new flight booking application in a high-traffic, high-turnover environment using Scrum methodology. Coordinated effectively with multiple teams including UI/UX, Backend, and Operations to ensure seamless user experience and system reliability during peak booking periods.',
    features: [
      'Flight booking interface',
      'High-traffic optimization',
      'Real-time availability',
      'Payment integration',
      'Multi-team coordination',
      'Performance monitoring',
      'User experience focus',
      'Scrum implementation',
    ],
    highlights: [
      'Maintained performance in high-traffic environment',
      'Coordinated effectively across multiple technical teams',
      'Implemented Scrum practices for rapid development cycles',
    ],
    technologies: [
      'AngularJS',
      'SASS',
      'HTML5',
      'CSS',
      'JavaScript',
      'jQuery',
      'Lodash',
      'npm',
      'Grunt',
      'Bower',
      'Jasmine',
      'Karma',
      'Zeplin',
      'Jira',
      'Confluence',
      'BitBucket',
    ],
    role: 'Web Developer',
    team: 'Large Scrum Team',
    fromTo: '05/2017 – 08/2017',
    duration: '4 months',
    location: 'Berlin, Germany',
    workMode: 'On-site',
    company: 'AirBerlin',
    industry: 'Airline / eCommerce',
  },
  {
    id: 'self-driving-car-demo',
    title: 'Self-Driving Car Control Demo App',
    projectType: 'Mobile App',
    compactDescription:
      'Demo app for controlling cutting-edge autonomous vehicle prototype with route programming and media control capabilities.',
    keyAchievements:
      'Autonomous vehicle integration • Ahead of time delivery • Cross-platform development • UI/UX collaboration • International teamwork',
    fullDescription:
      'Developed a demonstration application to control a visionary self-driving car prototype with cross-platform compatibility, especially for iOS. Provided functionality to program the route the car would drive autonomously and control various car media systems including lighting and music. Collaborated closely with multiple UI/UX designers and Chinese consultants in an international development environment.',
    features: [
      'Autonomous route programming',
      'Car media control',
      'Light system control',
      'Music system integration',
      'Cross-platform compatibility',
      'iOS optimization',
      'Real-time car communication',
      'Intuitive user interface',
    ],
    highlights: [
      'Integrated with cutting-edge autonomous vehicle technology',
      'Delivered cross-platform mobile solution with iOS focus',
      'Collaborated in international, multicultural team environment',
      'Implemented innovative car control interfaces',
    ],
    technologies: [
      'Angular',
      'TypeScript',
      'HTML5',
      'CSS',
      'JavaScript',
      'Ionic',
      'Cordova',
      'GitLab',
      'npm',
      'Webpack',
      'iOS',
      'XCode',
      'Swiper',
    ],
    role: 'Mobile App Developer',
    team: 'International UI/UX Team',
    fromTo: '03/2017 – 04/2017',
    duration: '2 months',
    location: 'Potsdam, Germany',
    workMode: 'On-site',
    company: "World's Largest Car Maker",
    industry: 'Automotive',
  },
  {
    id: 'pokemon-go-manager',
    title: 'Pokémon Go Manager',
    projectType: 'Web App',
    compactDescription:
      'Consumer-facing web application that helps Pokémon Go players organize and evaluate their captured Pokémon with a mobile-friendly interface and server-backed data storage.',
    keyAchievements:
      'Full-stack delivery • Mobile-first UX design • Reliable calculation engine for ranking captured Pokémon • Containerized deployment on AWS ECS',
    fullDescription:
      'Built as a single-developer product to help players prioritize which captured Pokémon to keep, train or evolve by estimating hidden quality metrics and providing ranking tools. The solution combines a React-based responsive frontend with an Express/Mongoose backend, OAuth2 login, and MongoDB persistence. The service was containerized and deployed to Amazon ECS with automated image builds on Docker Hub to ensure stable, repeatable releases.',
    features: [
      'Import and analyze captured Pokémon (scan/upload) to build a managed collection',
      'Estimate hidden quality metrics (individual values) to prioritize training/evolution',
      'Search, filter, rate and sort Pokémon by quality and custom tags',
      'Mobile-first responsive inputs and UI for easy use on phones',
      'Secure login and user data persistence via REST API',
      'Containerized CI/CD pipeline for reliable deployments',
    ],
    highlights: [
      'End-to-end single-developer delivery from design to production',
      'Improved mobile usability with custom responsive input components',
      'Production deployment on AWS (ECS) with Docker Hub continuous builds',
      'Clear, data-driven prioritization workflow that helped users decide which Pokémon to focus on',
    ],
    technologies: [
      'React',
      'JavaScript',
      'HTML5',
      'CSS',
      'Bootstrap',
      'Node.js',
      'Express',
      'MongoDB',
      'AWS',
      'Docker',
      'Webpack',
      'npm',
      'GitHub',
    ],
    role: 'Full-Stack Developer',
    team: 'Solo development',
    fromTo: '08/2016 - 01/2017',
    duration: '6 months',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Personal Project',
    industry: 'Gaming',
  },
  {
    id: 'stomap',
    title: 'Stomap – Project Management Tool',
    projectType: 'Web App',
    compactDescription:
      "Story-mapping based project management tool for handling large amounts of GitHub issues with a table-based UI and drag'n'drop editing.",
    keyAchievements:
      "Story mapping visualization • GitHub-native storage • Drag'n'Drop issue editing • Hierarchic issues and dependencies",
    fullDescription:
      "A project management tool focused on managing large numbers of GitHub issues using a second dimension: a table / story-mapping board. The approach reduces the number of issues to compare at any time, adds visual overview, and keeps information stored directly in GitHub. The project implements drag'n'drop editing, hierarchic issues, and dependency support while keeping public projects free to use.",
    features: [
      'Table / story-mapping board to arrange issues in a second dimension',
      "Drag'n'Drop issue editing",
      'Hierarchic issues with dependency visualization',
      'GitHub API integration (issues stored in GitHub)',
      'Reduced issue comparison surface for large issue sets',
      'Free for public projects',
    ],
    highlights: [
      'Applied story-mapping concept to GitHub issues',
      "Built an interactive table-based UI with drag'n'drop",
      'Kept all project data in GitHub to avoid information loss',
      'Designed for scaling to thousands of issues',
    ],
    technologies: [
      'TypeScript',
      'HTML',
      'CSS',
      'JavaScript',
      'Angular',
      'jQuery',
      'jQuery UI',
      'GitHub',
      'GitHub API',
      'tsd',
      'OAuth2',
      'Underscore',
      'yo',
      'Yeoman',
      'npm',
      'Grunt',
      'Bower',
      'Karma',
      'TeddyMocks',
      'mocha',
      'chai',
      'Travis CI',
      'Eclipse',
    ],
    role: 'Frontend Developer',
    team: 'Solo development',
    fromTo: '05/2015 - 02/2017',
    duration: '~2 years',
    location: 'Remote',
    workMode: 'Remote',
    company: 'Personal Project',
    industry: 'Productivity Tools',
  },
  {
    id: 'playotope-platform-game-maker',
    title: 'Playotope – Platform Game Maker for the Web',
    projectType: 'Web App',
    compactDescription:
      'Online platform game maker that provided a WYSIWYG editor enabling end users to create, customize, and share their own platform (jump’n’run) games with friends.',
    keyAchievements:
      'Built a browser-based game editor • Integrated social sharing & high scores • Worked on end-to-end game engine and web platform • Consulted and created software architecture and design (UML)',
    fullDescription:
      'Playotope is an online platform game maker that enabled end users to create, customize, and share their own platform (jump’n’run) games with friends. I worked as a freelancing developer for Playotope GmbH building the web platform and custom game engine, integrating social features (Facebook & Twitter), analytics and a sharing/commenting ecosystem. Additionally, I heavily consulted, discussed, and created software architecture and design, especially using UML diagrams, to ensure a flexible and reliable system. The project included backend and frontend work using Java and standard web technologies and was deployed on Google App Engine.',
    features: [
      'WYSIWYG game editor used by end users to create and share platform games',
      'Multiple theme/settings (Pirates, Politics, X-Mas, etc.)',
      'Comic visual style and custom assets',
      'Social integration (Facebook, Twitter) and sharing',
      'High scores and user comments',
      'Browser-first game engine with embed/publishing support',
    ],
    highlights: [
      'Developed core parts of a custom game engine for the web',
      'Implemented social sharing, high score and comment features',
      'Delivered full-stack features as a freelancing developer in a small team',
      'Consulted and contributed to software architecture and design (UML)',
    ],
    technologies: [
      'Java',
      'HTML',
      'CSS',
      'JavaScript',
      'Facebook',
      'Twitter',
      'Google Analytics',
      'Google App Engine',
      'Eclipse',
      'SVN',
      'TortoiseSVN',
      'Custom Test Framework',
      'Custom Game Engine',
      'UML',
      'Software Design',
      'Software Architecture',
      'Facebook API',
      'Twitter API',
    ],
    role: 'Full-Stack Developer',
    team: '2 developers, 1 artist',
    fromTo: '2009 – 2013',
    duration: '5 years',
    location: 'Remote',
    workMode: 'Freelance',
    company: 'Playotope GmbH',
    industry: 'Gaming',
  },
  {
    id: 'freelancing-it-professional',
    title: 'Freelancing IT Professional',
    projectType: 'Various Projects',
    compactDescription:
      'Long-term freelancing career delivering diverse IT solutions across multiple industries and technologies.',
    keyAchievements:
      '25+ years experience • Multi-industry expertise • Technology adaptation • Independent project delivery',
    fullDescription:
      'Extensive freelancing career spanning over two decades, delivering diverse IT solutions across multiple industries. Demonstrated ability to adapt to new technologies, work independently, manage client relationships, and deliver high-quality solutions across various project types and technological stacks.',
    features: [
      'Multi-industry experience',
      'Technology adaptation',
      'Independent project management',
      'Client relationship management',
      'Diverse solution delivery',
      'Continuous learning',
      'Quality assurance',
      'Flexible engagement models',
    ],
    highlights: [
      'Successfully delivered projects across 25+ years',
      'Adapted to evolving technology landscape',
      'Built strong client relationships and repeat business',
      'Maintained high quality standards across all engagements',
    ],
    technologies: [
      'Various Technologies',
      'Web Development',
      'Mobile Development',
      'Backend Systems',
      'Frontend Framework',
      'Database Systems',
      'Cloud Platforms',
      'DevOps Tools',
      'Project Management',
      'QA',
    ],
    role: 'Freelancing IT Professional',
    team: 'Various team configurations',
    fromTo: 'Since 2000',
    duration: '25+ years',
    location: 'Various locations',
    workMode: 'Flexible',
    company: 'Independent / Various Clients',
    industry: 'Various industries',
  },
];
