name: Install NPM Dependencies

on:
  workflow_call:

jobs:
  install-npm-deps:
    name: Install NPM Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 💾 Cache node_modules
        id: cache-npm-deps
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-deps-${{ hashFiles('package-lock.json', '.github/workflows/install-npm-deps.yml') }}

      - name: 📦 Install dependencies with npm ci
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
