name: Master CI Pipeline

on:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  install-npm-deps:
    uses: ./.github/workflows/install-npm-deps.yml

  install-playwright:
    needs: install-npm-deps
    uses: ./.github/workflows/install-playwright.yml

  commitlint:
    needs: install-npm-deps
    uses: ./.github/workflows/commitlint-since-last-commit.yml

  build-and-test:
    needs: [install-npm-deps, install-playwright]
    uses: ./.github/workflows/build-test.yml

  publish-to-gh-pages:
    needs: build-and-test
    uses: ./.github/workflows/publish-to-gh-pages.yml
